# import os
# import chromadb
# from dotenv import load_dotenv
# from langchain.schema import HumanMessage, SystemMessage
# from langchain_community.document_loaders import Docx2txtLoader, PyPDFLoader, UnstructuredPowerPointLoader
# from langchain.text_splitter import RecursiveCharacterTextSplitter
# from sentence_transformers import SentenceTransformer
# from langchain_nvidia_ai_endpoints import ChatNVIDIA
# from ddgs import DDGS  # ✅ For web search fallback

import os
import chromadb
from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage
from langchain_community.document_loaders import (
    Docx2txtLoader,
    PyPDFLoader,
    UnstructuredPowerPointLoader
)
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer
from langchain_nvidia_ai_endpoints import ChatNVIDIA
from ddgs import DDGS

# ----------------------------
# Setup
# ----------------------------
load_dotenv()

DATA_PATH = r"data"
CHROMA_PATH = r"chroma_db"

# Get API key from env
API_KEY = os.getenv("NVIDIA_API_KEY")

# ChromaDB client
chroma_client = chromadb.PersistentClient(path=CHROMA_PATH)
collection = chroma_client.get_or_create_collection(name="chroma")

# Embedding model
embedder = SentenceTransformer("all-MiniLM-L6-v2")

# NVIDIA LLM client (Default fast model)
llm = ChatNVIDIA(
    model="meta/llama-3.1-8b-instruct",
    api_key=API_KEY,
    temperature=1,
    top_p=0.9,
    max_tokens=4096,
)

# Text splitter for chunking
splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=100)

# ----------------------------
# Helper: Load and store documents
# ----------------------------
def load_and_store(file_path, session_id=None):
    ext = os.path.splitext(file_path)[1].lower()
    
    if ext == ".pdf":
        loader = PyPDFLoader(file_path)
    elif ext == ".docx":
        loader = Docx2txtLoader(file_path)
    elif ext in [".ppt", ".pptx"]:
        loader = UnstructuredPowerPointLoader(file_path)
    else:
        print(f"❌ Unsupported file type: {ext}")
        return
    
    docs = loader.load()
    chunks = splitter.split_documents(docs)
    
    filename = os.path.basename(file_path)
    for i, chunk in enumerate(chunks):
        emb = embedder.encode(chunk.page_content).tolist()
        metadata = {"source": filename}
        if session_id:
            metadata["session_id"] = str(session_id)
            
        chunk_id = f"{session_id}_{filename}_{i}" if session_id else f"{filename}_{i}"
        
        collection.add(
            documents=[chunk.page_content],
            metadatas=[metadata],
            ids=[chunk_id],
            embeddings=[emb]
        )
    print(f"✅ Added {len(chunks)} chunks from {file_path}")

# ----------------------------
# Helper: Detect if any docs exist in ChromaDB
# ----------------------------
def has_uploaded_docs(session_id=None):
    try:
        where_clause = {"session_id": str(session_id)} if session_id else None
        if where_clause:
            results = collection.get(where=where_clause, include=["documents"])
            return len(results["documents"]) > 0
        else:
            count = len(collection.get(include=["documents"])["documents"])
            return count > 0
    except Exception:
        return False

# ----------------------------
# Helper: Answer query
# ----------------------------
def answer_query(query, chat_history=None, level="standard", mode="standard", stream=False, session_id=None, pinned_contexts=None, web_search=False):
    query_lower = query.strip().lower()
    has_local_data = False
    # GLOBAL FORMATTING COMMAND — appended to every system prompt
    global_formatting = r"""

[MANDATORY FORMATTING RULES]

- Strictly obey all formatting instructions in every response.

- Output only in clean plain English UTF-8 text using standard markdown.

- Never use:
  LaTeX,
  Unicode mathematical/stylized characters,
  decorative symbols,
  invisible formatting artifacts,
  broken markdown,
  malformed text rendering.

- Never split words, numbers, units, or currency values across lines.

- Write all numbers in plain readable text.
  Correct: 1.35 billion
  Correct: $250 million
  Wrong: 1.35 𝑏𝑖𝑙𝑙𝑖𝑜𝑛

- Use bold markdown only for:
  headers,
  step labels.

- If explaining a process, always format as:

  **Step 1:** Title

  content

  **Step 2:** Title

  content

- Insert exactly one blank line between:
  every paragraph,
  every bullet point,
  every numbered step.

- Never compress multiple sections into one paragraph.

- Use triple backtick code blocks only when actual code is shown.

- Never place explanatory text inside code blocks.

- Do not output:
  internal reasoning,
  hidden notes,
  chain artifacts,
  tool traces,
  autogenerated appendices,
  worksheet formatting.

- Response must always appear as polished professional ChatGPT markdown.

- Before sending each response, internally verify:
  no unicode math characters,
  no malformed markdown,
  no collapsed spacing,
  no stray autogenerated sections,
  proper paragraph separation.

- Only output the final cleaned response.

[MATH FORMATTING - ONLY IF YOUR RESPONSE INCLUDES MATH OR EQUATIONS]
- ALL math MUST use LaTeX delimiters. There is NO other option.
- Inline math: wrap in single dollar signs → $x^2 + y = 5$
- Block/display math (equations, integrals, matrices): wrap in double dollar signs → $$\int_0^{\pi} \sin(x)\,dx = 2$$
- Fractions: $$\frac{a}{b}$$
- Square roots: $$\sqrt{x}$$
- Matrices: $$\begin{pmatrix} a & b \\ c & d \end{pmatrix}$$
- Greek letters: $\alpha$, $\beta$, $\pi$, $\theta$
- NEVER write raw symbols like ∫, ∑, √, π outside of $...$ delimiters
- NEVER write "x^2" without dollar signs. ALWAYS write "$x^2$"

CRITICAL: If the user's question is NOT about math (e.g., weather, history, reviews), DO NOT force math, matrices, or variables into your answer. Just answer naturally in plain English!
"""

    # Step 0: Study Level Instructions
    level_instruction = ""
    if level == "eli5":
        level_instruction = "IMPORTANT: Use the 'Explain Like I'm 5' approach. Use simple analogies, avoid complex jargon, and break down concepts into their most basic parts."
    elif level == "advanced":
        level_instruction = "IMPORTANT: Provide an in-depth, academic, and technical response. Use precise terminology, explore nuances, and assume the user has prior knowledge of the subject."
    else:
        level_instruction = "IMPORTANT: Provide a clear, balanced, and helpful explanation suitable for a standard student level."

    # Step 0.1: Thinking Mode Instruction
    if mode == "thinking":
        level_instruction += "\nTHINKING MODE ACTIVE: Before providing your final answer, think step-by-step. Analyze the question, consider different perspectives, and show your internal reasoning process. Be extremely thorough and analytical."

    # Step 0.2: Casual greetings
    if query_lower in ["hi", "hello", "hey", "what's up", "yo", "good morning", "good evening"] and not stream:
        return {
            "response": "Hey there! 😊 How can I help you today?",
            "sources": []
        }

    # Step 0.3: Model Selection
    # Standard: fast and capable 70B model. Thinking: The massive 405B model.
    model_name = "meta/llama-3.1-405b-instruct" if mode == "thinking" else "meta/llama-3.1-70b-instruct"
    
    current_llm = ChatNVIDIA(
        model=model_name,
        api_key=API_KEY,
        temperature=0.7 if mode == "thinking" else 1.0, # Lower temperature for thinking
        top_p=0.9,
        max_tokens=4096,
    )

    print(f"\n🚀 Thinking (Level: {level}, Mode: {mode}, Model: {model_name})...\n")
    # Step 1: Check if any documents exist at all
    docs_exist = has_uploaded_docs(session_id)

    # Step 2: If docs exist, try local search
    retrieved_docs = []
    valid_metas = []
    if docs_exist:
        # Retrieve more context in thinking mode
        n_results = 10 if mode == "thinking" else 4
        where_clause = {"session_id": str(session_id)} if session_id else None
        
        results = collection.query(
            query_texts=[query],
            n_results=n_results,
            where=where_clause
        )
        
        raw_docs = results.get("documents", [[]])[0]
        raw_dists = results.get("distances", [[]])[0]
        raw_metas = results.get("metadatas", [[]])[0]
        
        # Filter by distance threshold (L2 distance: < 1.4 is usually semantically related)
        for doc, dist, meta in zip(raw_docs, raw_dists, raw_metas):
            if dist < 1.4:
                retrieved_docs.append(doc)
                valid_metas.append(meta)

    has_local_data = len(retrieved_docs) > 0

    # Step 2.6: Smart Intent Detection (If web_search toggle is OFF)
    auto_web_search = False
    if not web_search and not has_local_data:
        # 1. Local Heuristic Check (Fast & Offline-friendly)
        real_time_indicators = ["current", "latest", "best", "price", "news", "today", "who is", "who are", "ranking", "winner", "stock"]
        if any(word in query_lower for word in real_time_indicators):
            auto_web_search = True
            print(f"🔍 [SMART SEARCH] Intent: YES (Reason: Real-time Keywords)")
        else:
            # 2. AI Intent Fallback
            try:
                intent_check = llm.invoke([
                    SystemMessage(content="Determine if this query needs real-time web info or data from 2024-2026. Respond only 'YES' or 'NO'."),
                    HumanMessage(content=query)
                ]).content.strip().upper()
                auto_web_search = "YES" in intent_check
                if auto_web_search:
                    print(f"🔍 [SMART SEARCH] Intent: YES (Reason: AI Analysis)")
            except Exception as e:
                print(f"⚠️ [SMART SEARCH] AI Intent check failed: {e}")
                auto_web_search = False
    
    if web_search:
        print(f"🔍 [SMART SEARCH] Intent: YES (Reason: Manual Toggle)")

    # Step 2.5: Handle pinned contexts
    pinned_context_str = ""
    if pinned_contexts and len(pinned_contexts) > 0:
        pinned_context_str = "\n[CRITICAL PINNED CONTEXT START]\n"
        pinned_context_str += "The user has explicitly pinned the following prior messages as the PRIMARY context for this response:\n"
        for pc in pinned_contexts:
            pinned_context_str += f"📍 PINNED REFERENCE: \"{pc}\"\n"
        pinned_context_str += "\nINSTRUCTION: Prioritize the information above. If the recent conversation history diverges from this pinned context, follow the pinned context.\n"
        pinned_context_str += "[CRITICAL PINNED CONTEXT END]\n\n"

    if has_local_data:
        # ✅ Found relevant local chunks
        system_prompt = f"""
        You are Intellectra, a world-class AI tutor. 
        (Internal Note: You are currently running on the '{model_name}' model. If the user asks which model you are, explicitly state this model name.)
        Your goal is to help the user learn and understand.
        {level_instruction}
        
        {pinned_context_str}
        Use the following document segments to answer accurately. 
        If the data is insufficient, say so and use your own knowledge.
        --------------------
        {retrieved_docs}
        """
    # Step 3: Web Search and Token Generation
    web_sources = []
    def main_gen():
        nonlocal web_sources
        search_results = []
        # Trigger search if specifically requested OR if our auto-detection flagged it
        should_search_web = web_search or auto_web_search
        
        if should_search_web:
            status_msg = f"ddgs search --query \"{query}\""
            if stream:
                yield {"status": status_msg, "type": "tool_start"}
            else:
                print(f"🌐 {status_msg}")
                
            try:
                if len(query.split()) > 1:
                    with DDGS() as ddgs:
                        for r in ddgs.text(query, max_results=5):
                            search_results.append(f"{r['title']}: {r['body']} ({r['href']})")
                            web_sources.append(r['href'])
            except Exception as e:
                print("⚠️ Web search failed:", e)

            if stream and search_results:
                yield {"status": f"Found {len(search_results)} relevant web sources for your query.", "type": "tool_output"}
                # Send the links to the UI immediately
                yield {"sources": web_sources}

        # Step 4: System Prompt Construction
        current_system_prompt = ""
        if has_local_data:
            current_system_prompt = f"""
            You are Intellectra, a world-class AI tutor. 
            (Internal Note: You are currently running on the '{model_name}' model.)
            {level_instruction}
            
            {pinned_context_str}
            Use the following document segments to answer accurately. 
            --------------------
            {retrieved_docs}
            """
            if search_results:
                current_system_prompt += f"\n\nAlso consider these recent web results:\n{search_results}"
        elif search_results:
            current_system_prompt = f"""
            You are Intellectra, a world-class AI tutor.
            (Internal Note: You are currently running on the '{model_name}' model.)
            {level_instruction}
            
            {pinned_context_str}
            I searched the web to help answer your question. Use these results:
            --------------------
            {search_results}
            """
        else:
            current_system_prompt = f"""
            You are Intellectra, a friendly and concise AI tutor.
            (Internal Note: You are currently running on the '{model_name}' model.)
            {level_instruction}
            
            {pinned_context_str}
            Respond naturally using your own general knowledge.
            """

        # Step 5: Final Message Construction
        final_messages = [SystemMessage(content=current_system_prompt)]
        if chat_history:
            for msg in chat_history[-10:]:
                if msg["sender"] == "user":
                    final_messages.append(HumanMessage(content=msg["text"]))
                elif msg["sender"] == "ai":
                    final_messages.append(AIMessage(content=msg["text"]))
        
        # Merge pins directly into the query so it's impossible to ignore
        effective_query = query
        if pinned_context_str:
            effective_query = f"PLEASE REFERENCE THE FOLLOWING PINNED CONTEXT FOR THIS QUESTION:\n{pinned_context_str}\n\nUSER QUESTION: {query}"
            
        # FORCE math formatting at the very end of the prompt
        effective_query += "\n\n" + global_formatting
            
        final_messages.append(HumanMessage(content=effective_query))

        if stream:
            for chunk in current_llm.stream(final_messages):
                yield chunk
        else:
            response = current_llm.invoke(final_messages)
            yield response.content

    # Extract sources if they exist (need them for both stream and non-stream)
    sources = []
    if has_local_data and valid_metas:
        try:
            sources = list(set([m["source"] for m in valid_metas if "source" in m]))
        except Exception:
            sources = []
            
    # Combine with web sources
    if web_sources:
        sources.extend(list(set(web_sources)))

    if stream:
        return main_gen(), sources
    else:
        # For non-stream, we just get the first yielded item (the full response)
        g = main_gen()
        res = next(g)
        return {
            "response": res,
            "sources": sources
        }

# ----------------------------
# Helper: Generate Flashcards
# ----------------------------
def generate_flashcards(text):
    system_prompt = """
    You are an AI tutor tool designed to extract key concepts from educational text and convert them into flashcards.
    Extract the most important facts, definitions, or concepts from the provided text and formulate them as clear, concise Question/Answer pairs.
    You MUST output valid JSON only. Do not wrap it in markdown code blocks.
    The JSON structure MUST be an array of objects, like this:
    [
        {"front": "What is ...?", "back": "It is ..."},
        {"front": "...", "back": "..."}
    ]
    Limit to a maximum of 5 most critical flashcards.
    """
    try:
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=f"Extract flashcards from this text:\n\n{text}")
        ]
        response = llm.invoke(messages)
        content = response.content.strip()
        import json
        import re
        
        # Robustly extract JSON array using regex
        match = re.search(r'\[\s*\{.*\}\s*\]', content, re.DOTALL)
        if match:
            json_str = match.group(0)
        else:
            # Fallback cleanup
            json_str = content.strip()
            if json_str.startswith("```json"):
                json_str = json_str[7:]
            elif json_str.startswith("```"):
                json_str = json_str[3:]
            if json_str.endswith("```"):
                json_str = json_str[:-3]
        
        cards = json.loads(json_str.strip())
        return cards
    except Exception as e:
        print(f"Error generating flashcards: {e}")
        return []

# print("🤖 Tutor AI ready! Type your questions, or upload files with: upload <path>")
# while True:
#     user_input = input("\n> ")
    
#     if user_input.lower() == "quit":
#         break
#     elif user_input.startswith("upload "):
#         file_path = user_input.split("upload ", 1)[1].strip()
#         load_and_store(file_path)
#     else:
#         answer = answer_query(user_input)
#         print(f"\nAI Response:\n{answer}")
# # ----------------------------
# # Disabled terminal chat (handled by Flask)
# # ----------------------------
# ----------------------------
# Helper: Generate Quiz
# ----------------------------
def generate_quiz(text):
    system_prompt = """
    You are an AI tutor tool designed to extract key concepts from educational text and convert them into a multiple-choice quiz.
    Extract the most important facts or concepts from the provided text and formulate 3 Multiple-Choice Questions (MCQs).
    You MUST output valid JSON only. Do not wrap it in markdown code blocks.
    The JSON structure MUST be an array of objects, exactly like this:
    [
        {
            "question": "What is the capital of France?",
            "options": ["London", "Berlin", "Paris", "Madrid"],
            "answer": 2
        }
    ]
    IMPORTANT: The 'answer' field must be an integer representing the 0-based index of the correct option in the 'options' array.
    Limit to exactly 3 questions.
    """
    try:
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=f"Extract a quiz from this text:\n\n{text}")
        ]
        response = llm.invoke(messages)
        content = response.content.strip()
        
        import json
        import re
        
        # Robustly extract JSON array using regex
        match = re.search(r'\[\s*\{.*\}\s*\]', content, re.DOTALL)
        if match:
            json_str = match.group(0)
        else:
            # Fallback cleanup
            json_str = content.strip()
            if json_str.startswith("```json"):
                json_str = json_str[7:]
            elif json_str.startswith("```"):
                json_str = json_str[3:]
            if json_str.endswith("```"):
                json_str = json_str[:-3]
        
        quiz_data = json.loads(json_str.strip())
        return quiz_data
    except Exception as e:
        print(f"Error generating quiz: {e}")
        return []

# ----------------------------
# Helper: Concept Check Generation
# ----------------------------
def generate_concept_questions(text):
    system_prompt = """
    You are an AI tutor designed to assess a student's understanding of a specific concept.
    Based on the provided text, generate 3 open-ended diagnostic questions that will help gauge how well the user truly understands the core ideas.
    IMPORTANT: If you see a block marked '[CRITICAL PINNED CONTEXT]', prioritize that information as the primary subject matter for your questions.
    Avoid simple yes/no questions. Ask "why" or "how" questions that require a short explanation.
    You MUST output valid JSON only. Do not wrap it in markdown code blocks.
    The JSON structure MUST be an array of strings, like this:
    [
        "Why is X important in the context of Y?",
        "How would you explain Z to a beginner?",
        "What happens if we remove W from the system?"
    ]
    Limit to exactly 3 questions.
    """
    try:
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=f"Generate diagnostic questions for this text:\n\n{text}")
        ]
        response = llm.invoke(messages)
        content = response.content.strip()
        
        import json
        import re
        
        match = re.search(r'\[\s*".*"\s*\]', content, re.DOTALL)
        if match:
            json_str = match.group(0)
        else:
            json_str = content.strip()
            if json_str.startswith("```json"):
                json_str = json_str[7:]
            elif json_str.startswith("```"):
                json_str = json_str[3:]
            if json_str.endswith("```"):
                json_str = json_str[:-3]
        
        questions = json.loads(json_str.strip())
        return [{"question": q, "answer": ""} for q in questions]
    except Exception as e:
        print(f"Error generating concept questions: {e}")
        return []

# ----------------------------
# Helper: Concept Check Evaluation
# ----------------------------
def evaluate_concept_answers(questions, answers, original_text):
    # If the user submitted completely blank answers, bypass the LLM to prevent hallucinations.
    if all(not str(a).strip() for a in answers):
        return "It looks like you didn't provide any answers to the concept check! If you're unsure about this topic, just say so and I'll be happy to break it down and explain it to you."

    system_prompt = """
    You are an expert AI tutor. The user was learning about a concept and I asked them a few diagnostic questions.
    I will provide the original text they read, the questions asked, and their answers.
    Your task is to:
    1. Briefly acknowledge their effort.
    2. Provide a SHORT, simple evaluation of what they know and what they don't know based on their answers.
    3. CRITICAL: If a user's answer is blank, empty, or says "I don't know", you MUST state that they skipped or missed that part of the concept. Do NOT pretend they answered it correctly.
    4. Conclude by explicitly asking: "If you want me to explain this concept according to this evaluation, just say so, or tell me 'I already know that'."
    DO NOT provide the full explanation yet. Keep it concise.
    """
    
    q_and_a = ""
    for idx, (q, a) in enumerate(zip(questions, answers)):
        user_ans = str(a).strip()
        if not user_ans:
            user_ans = "[NO ANSWER PROVIDED]"
        q_and_a += f"Q{idx+1}: {q}\nUser's Answer: {user_ans}\n\n"
        
    prompt = f"""
    ORIGINAL CONCEPT TEXT:
    {original_text}
    
    DIAGNOSTIC Q&A:
    {q_and_a}
    
    Please evaluate and provide the tailored explanation.
    """
    
    try:
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=prompt)
        ]
        response = llm.invoke(messages)
        return response.content.strip()
    except Exception as e:
        print(f"Error evaluating concept answers: {e}")
        return "I encountered an error while evaluating your answers. Please try again."

if __name__ == "__main__":
    print("✅ API module loaded. Flask will handle all interactions.")
